[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    [[redirects]]
  from = "/"
  to = "/"
  status = 200
  force = true
  [[redirects]]
  from = "/tvseries"
  to = "/"
  status = 200
  force = true
  [[redirects]]
  from = "/toprated"
  to = "/"
  status = 200
  force = true
  [[redirects]]
  from = "/upcoming"
  to = "/"
  status = 200
  force = true
  [[redirects]]
  from = "/tvseriesdetail"
  to = "/"
  status = 200
  force = true
  [[redirects]]
  from = "/movies"
  to = "/"
  status = 200
  force = true